[redis]
url = "redis://localhost:6379"
channel = "mev_swaps"
pool_size = 10
connection_timeout = 5000
read_timeout = 3000

[ethereum]
rpc_url = "http://localhost:8545"
ws_url = "ws://localhost:8546"
chain_id = 1
max_block_range = 1000
block_timeout = 30000

[mempool]
enabled = true
rpc_url = "http://localhost:8545"
max_concurrent_requests = 50
request_timeout = 10000
batch_size = 100

[flashbots]
enabled = true
rpc_url = "https://relay.flashbots.net"
auth_header = ""
max_concurrent_requests = 20
request_timeout = 15000

[metrics]
enabled = true
host = "127.0.0.1"
port = 9090

[logging]
level = "info"
format = "json"
output = "stdout" 