[redis]
url = "redis://redis:6379"
channel = "mev_swaps"
pool_size = 50
connection_timeout = 10000
read_timeout = 5000

[ethereum]
rpc_url = "https://mainnet.infura.io/v3/YOUR_INFURA_KEY"
ws_url = "wss://mainnet.infura.io/ws/v3/YOUR_INFURA_KEY"
chain_id = 1
max_block_range = 10000
block_timeout = 60000

[mempool]
enabled = true
rpc_url = "https://mainnet.infura.io/v3/YOUR_INFURA_KEY"
max_concurrent_requests = 200
request_timeout = 15000
batch_size = 500

[flashbots]
enabled = true
rpc_url = "https://relay.flashbots.net"
auth_header = "Bearer YOUR_FLASHBOTS_KEY"
max_concurrent_requests = 100
request_timeout = 30000

[metrics]
enabled = true
host = "0.0.0.0"
port = 9090

[logging]
level = "warn"
format = "json"
output = "stdout"

[subgraph]
enabled = true
url = "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3"
poll_interval = 60
cache_ttl_seconds = 300
max_concurrent_requests = 20
request_timeout = 15000
retry_attempts = 5
retry_delay_ms = 2000 